### ISSUE TITLE
[Suggestion]: Update ffq 

### ISSUE THREAD

**Issue by tamuanand** [telatin/getreads#1]
Hi @telatin 

Thanks for the great utility. A small suggestion: ffq was updated from 0.2.1 to 0.3 about 9 months ago - *https://github.com/pachterlab/ffq**

Not sure if that update matters for the getreads stuff you have, but I thought I will let you know.

**Comment by telatin** [comment]
Hello @tamuanand !
Thanks for the feedback! I should be able to finalize the update I'm working on in a month or so, and that will make it into it!
